Feature: Bip32 Signer
libsv/go-bt pull request #46
Opened 2021-09-17 16:20 UTC by Tigh-Gherr

Allows for the signing of inputs, which themselves have been built from derived keys.

Example usage:
```
n, err := tx.Bip32SignAuto(ctx, &bt.LocalBip32SignerDeriver{MasterPrivateKey: privKey}, s.derivationPathGetter)
if err != nil {
	return nil, err
}
if len(n) == 0 {
	return nil, errors.New("no inputs signed")
}

. . .

func (s *service) derivationPathGetter(ctx context.Context, lockingScript string) (string, error) {
	return s.store.DerivationPath(ctx, lockingScript)
}

```

2021-09-17 16:23 UTC, jadwahab commented
Not sure I follow, is this to derive a child key and sign in one step?

2021-09-17 17:15 UTC, Tigh-Gherr commented
@jadwahab yeah, it's just to have a SignAuto function for derived keys, so that the implementor doesn't have to manage the building of them.

2021-09-20 14:43 UTC, jadwahab requested changes
Change SignAuto to Sign and rename SignAuto to SignAll

2021-09-22 13:51 UTC, jadwahab commented on signer.go
> -type AutoSigner interface {
peace the fuck out 😂

2021-09-22 15:47 UTC, jadwahab approved these changes

2021-09-22 15:47 UTC, merged