Feature: JSON Marshalling and Unmarshalling for bt.UTXO
libsv/go-bt pull request #50
Opened 2021-09-23 12:55 UTC by Tigh-Gherr

Keynames were chosen out of regtest compatibility, specifically around `listunspent`.

2021-09-24 09:14 UTC, theflyingcodr requested changes
One question

2021-09-24 09:14 UTC, theflyingcodr commented on utxo.go
> +	Amount       float64 `json:"amount"`
In our other outputJSON under output.go we use 'Value' for the bsv value, we should probably have that match here rather than Amount?

2021-09-26 12:38 UTC, jadwahab requested changes
We discussed a bit on friday that we should remove any strings attached to the code from any weird/legacy bitcoind JSON stuff and we can just have a wrapper around our code to match the legacy node stuff and then we can deprecate that at some point. This links up to issue #52 that we should sort out asap before stablising v2

2021-09-28 09:29 UTC, jadwahab approved these changes

2021-09-28 09:30 UTC, merged